
version: '2'
networks:
  cb-network:
volumes:
  codebeamer-volume:
  mysql-codebeamer-volume:

services:
  codebeamer:
    image: dextershin/codebeamer:${CODEBEAMER_VERSION}
    hostname: ${CB_HOSTNAME}
    mac_address: ${CB_MACADDRESS}
    restart: unless-stopped
    networks:
      - cb-network
    ports:
      - 8081:8080
      - 1099:1099
      - 3690:3690
    volumes:
      - codebeamer-volume:/opt/codebeamer
    environment:
      DEBUG_LEVEL: 256
    links:
      - mysql-codebeamer:mysql

  mysql-codebeamer:
    image: mysql:5.7
    networks:
      - cb-network
    volumes:
      - mysql-codebeamer-volume:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ${CB_MYSQL_ROOT_PASSWORD}
